  influxdb1:
    image: influxdb:0.12.2
    container_name: influxdb012
    ports:
      - '18086:8086'
      - '12004:2004'
      - '18083:8083'
    environment:
      INFLUXDB_ADMIN_USER: grafana
      INFLUXDB_ADMIN_PASSWORD: grafana
      INFLUXDB_DB: site
    volumes:
      - ./docker/blocks/influxdb012/influxdb.conf:/etc/influxdb/influxdb.conf


  fake-influxdb1-data:
    image: grafana/fake-data-gen
    links:
      - influxdb1
    environment:
      FD_SERVER: influxdb1
      FD_DATASOURCE: influxdb
      FD_PORT: 8086

  telegraf-influxdb1:
    image: telegraf:latest
    links:
      - influxdb1
    volumes:
      - ./docker/blocks/influxdb1/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/log:/var/log/host
      - ../data/log:/var/log/grafana
