version: "2.1"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: "fluentd"
      options:
        tag: nginx

  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: grafana
      MYSQL_USER: grafana
      MYSQL_PASSWORD: password
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all, --max-connections=1001]
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  mysqld-exporter:
    image: prom/mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=root:rootpass@(db:3306)/
    ports:
      - 9104
    depends_on:
      db:
        condition: service_healthy

  grafana:
    image: grafana/grafana-oss:dev
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ${PLUGIN_EXAMPLES_REPO}/examples/app-with-on-behalf-of-auth/dist:/var/lib/grafana/plugins/grafana-appwithonbehalfofauth-app
      - ${PLUGIN_EXAMPLES_REPO}/examples/app-with-service-account/dist:/var/lib/grafana/plugins/grafana-appwithserviceaccount-app
    environment:
      - VIRTUAL_HOST=grafana.loc
      - GF_SERVER_ROOT_URL=http://grafana.loc
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=password
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=db:3306
      - GF_DATABASE_MAX_OPEN_CONN=300
      - GF_SERVER_ROUTER_LOGGING=true
      - GF_LOG_LEVEL=debug
      - GF_LOG_CONSOLE_FORMAT=json
      - GF_LOG_FILTERS=alerting.notifier:debug,alerting.notifier.slack:debug,auth:debug
      - GF_AUTH_TOKEN_ROTATION_INTERVAL_MINUTES=2
      - GF_DEFAULT_APP_MODE=development
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_FEATURE_TOGGLES_ENABLE=externalServiceAuth externalServiceAccounts
      - GF_AUTH_EXTENDED_JWT_ENABLED=true
      - GF_AUTH_EXTENDED_JWT_EXPECT_AUDIENCE=http://localhost:3000/
      - GF_AUTH_EXTENDED_JWT_EXPECT_ISSUER=http://localhost:3000/
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-appwithonbehalfofauth-app grafana-appwithserviceaccount-app
    ports:
      - 3000
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: "fluentd"
      options:
        tag: grafana

  prometheus:
    image: prom/prometheus:v2.4.2
    volumes:
      - ./prometheus/:/etc/prometheus/
    environment:
      - VIRTUAL_HOST=prometheus.loc
    ports:
      - 9090

  loki:
    image: grafana/loki:master
    environment:
      - VIRTUAL_HOST=loki.loc
    ports:
      - 3100
    command: -config.file=/etc/loki/local-config.yaml

  fluentd:
    image: grafana/fluent-plugin-loki:master
    volumes:
      - ./fluentd/fluentd.conf:/fluentd/etc/fluentd.conf
    links:
      - loki
    ports:
      - "24224:24224"
      - "24224:24224/udp"
