  influxdb211:
    image: influxdb:2.1.1
    container_name: influxdb211
    ports:
      - '18086:8086'
    environment:
      INFLUXD_REPORTING_DISABLED: 'true'
      INFLUXD_HTTP_BIND_ADDRESS: ':8086'
      DOCKER_INFLUXDB_INIT_MODE: 'setup'
      DOCKER_INFLUXDB_INIT_USERNAME: 'grafana'
      DOCKER_INFLUXDB_INIT_PASSWORD: 'grafana12345'
      DOCKER_INFLUXDB_INIT_ORG: 'myorg'
      DOCKER_INFLUXDB_INIT_BUCKET: 'mybucket'
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 'mytoken'
    volumes:
      - ./docker/blocks/influxdb/setup_influxql.sh:/docker-entrypoint-initdb.d/setup_influxql.sh

  telegraf:
    image: telegraf:latest
    links:
      - influxdb211
    depends_on:
      - influxdb211
    volumes:
      - ./docker/blocks/influxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/log:/var/log/host
      - ../data/log:/var/log/grafana
