apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: grafana-project
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Test argocd project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
    - namespace: default
      server: https://host.docker.internal:8080
      name: grafana-apiserver
