name: publish-icons-package
on:
  push:
    branches:
      - main
    paths:
      # Trigger the action on changes to the icons package
      - "packages/grafana-icons/**"

jobs:
  publish:
    name: Publish the Icons package to NPM & GitHub Package Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
      # limit releases to version changes - https://github.com/EndBug/version-check
      - name: Check version changes
        uses: EndBug/version-check@v2
        id: version_check
        with:
          # diff the commits rather than commit message for version changes
          diff-search: true
          # Custom path to the icons package.json
          file-name: "packages/grafana-icons/package.json"

      - name: Version update detected
        if: steps.version_check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.version_check.outputs.version }} (${{ steps.version_check.outputs.type }})"'

      - name: Setup .npmrc file for NPM registry
        if: steps.version_check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        if: steps.version_check.outputs.changed == 'true'
        run: yarn install --immutable

      - name: Build the package
        if: steps.version_check.outputs.changed == 'true'
        run: yarn build

      - name: Publish package to NPM
        if: steps.version_check.outputs.changed == 'true'
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup .npmrc file for GitHub Packages
        if: steps.version_check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@grafana"

      - name: Publish package to Github Packages
        if: steps.version_check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
