name: publish-technical-documentation-next

on:
  push:
  workflow_dispatch:
jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      has-secrets: ${{ steps.check.outputs.has-secrets }}
    steps:
      - name: Check for secrets
        id: check
        shell: bash
        run: |
          if [ -n "${{ (secrets.PUBLISH_TECHNICAL_DOCUMENTATION_ID != '' && secrets.PUBLISH_TECHNICAL_DOCUMENTATION_PEM != '') || '' }}" ]; then
            echo has-secrets=1 >> "${GITHUB_OUTPUT}"
          fi
  sync:
    needs: config
    if: github.repository == 'grafana/grafana' && needs.config.outputs.has-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: jdbaldry/github-app-token@e39cd6afe97f7f59c8b67f2af76d6bd60233e8c7
        with:
          app_id: ${{ secrets.PUBLISH_TECHNICAL_DOCUMENTATION_ID }}
          private_key: ${{ secrets.PUBLISH_TECHNICAL_DOCUMENTATION_PEM }}
          organization: grafana

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout website-sync action
        uses: actions/checkout@v3
        with:
          path: .github/actions/website-sync
          repository: grafana/website-sync
          sparse-checkout: |
            action.yml
            entrypoint.sh
          token: ${{ steps.generate-token.outputs.token }}

      - name: Publish to website repository (next)
        uses: ./.github/actions/website-sync
        id: publish-next
        with:
          repository: grafana/website
          branch: jdb/2023-08-use-github-app
          host: github.com
          # PUBLISH_TO_WEBSITE_TOKEN is a fine-grained GitHub Personal Access Token that expires.
          # It must be regenerated in the grafanabot GitHub account and requires a Grafana organization
          # GitHub administrator to update the organization secret.
          # The IT helpdesk can update the organization secret.
          github_pat: grafanabot:${{ steps.generate-token.outputs.token }}
          source_folder: docs/sources
          target_folder: content/docs/grafana/next
