name: Update `make docs` procedure
on:
  schedule:
    - cron: '0 7 * * 1-5'
  workflow_dispatch:
jobs:
  main:
    if: github.repository == 'grafana/grafana'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/writers-toolkit/update-make-docs@429afd4bcabff0d40429d8dcd3a165fac4cedc5b
        with:
          pr_options: >
            --label 'backport v10.0.x'
            --label 'backport v10.1.x'
            --label 'backport v10.2.x'
            --label no-changelog
            --label type/docs
          trace: true